### ISSUE TITLE
change dependency from flutterblue to flutterblueplus

### ISSUE THREAD

**Issue by BentEngbers** [CodeMinion/another_brother#23]
The flutterblue package has not had a new version in a long while (14 months ago), and this is making the build process more and more difficult. 
according to  [flutterblueplus](https://github.com/boskokg/flutter_blue_plus), they are the successor, because development has stopped on the original project:
>FlutterBluePlus is a bluetooth plugin for [Flutter](https://flutter.dev/), a new app SDK to help developers build modern multi-platform apps. Note: this plugin is continuous work from FlutterBlue since maintaince stoped.

Would it be possible to change the flutterblue dependency to the new flutterblueplus dependency?

**Comment by CodeMinion** [comment]
Hey @BentEngbers ! 

Thanks for reaching out about this. I'll make the switch over this weekend and release a new version using https://pub.dev/packages/flutter_blue_plus and test it out with the printers just to double confirm they still work fine.

Looking at flutter_blue_plus looks like they have updated the protobuff deps that we currently have to manually do so that will be a nice improvement. 

Note: I'll leave this issue open until I release the new version.

Thanks again!

**Comment by CodeMinion** [comment]
Hey @BentEngbers ! 

Wanted to let you know that another_brother 0.0.27 now uses flutter_blue_plus instead of flutter_blue. 

Thanks again for the suggestions~
