### ISSUE TITLE
Can't build on iOS Simulator on MBP M1 for xcode 13.4.1

### ISSUE THREAD

**Issue by shubhjagani** [CodeMinion/another_brother#28]
Spent hours going through all the issues, using the `ios-no-type-b` branch but still unable to build and test on iOS. Begging for a proper fix here 🙏. Please advise what I should do here, need my app to work with Brother QL-810W using both iOS and Android devices but don't necessarily need to go through the app store review.

**Comment by CodeMinion** [comment]
Hi @shubhjagani ! Thanks for reaching out about this. 

I don't believe you will be able to build on the iOS simulator due to some of the prepackage libs so you will need to build to an actual device. 

In addition to that I believe that neither the Android Emulator nor the iOS Simulator have support for NSD and Bluetooth so your printer discovery wont work in the case where you are connecting and Bluetooth connection shouldn't work in the case you are trying to connect over BT on the Emulator/Simulator.

Do you have a physical iOS device you can build it to? I personally build it using one of the cheapest iPhones available https://www.youtube.com/watch?v=kCLR7ACkMOw

**Comment by shubhjagani** [comment]
@CodeMinion thanks!! You're the best. For anyone else running into issues: 
1. Switch to the `ios-no-type-b` branch. It has most of the printers you want to use away. 
2. Use a physical iOS device
