### ISSUE TITLE
ERROR_WRONG_CUSTOM_INFO for  printerModel={name=RJ_4030, id=13}

### ISSUE THREAD

**Issue by christiandjakou** [CodeMinion/another_brother#33]
I have the error ERROR_WRONG_CUSTOM_INFO when trying to print on a RJ_4030
There is no BinPaper_RJ4030 class, nor .bin files in the library. That would explain why i keep having this error when trying to print. 
I tried using BinPaper for different models like the BinPaper_RJ4040 but I keep having the error above. Please any idea of a solution or workaround? 
Danke schön

**Comment by CodeMinion** [comment]
Thanks for reaching out about this @christiandjakou . If I remember correctly the bin files are specific to each printer but it has been a while since I looked into them so I may be wrong. Not sure if you have already tried these but we also have a set of papers for the RJ_4030Ai https://github.com/CodeMinion/another_brother/blob/main/lib/custom_paper.dart#L320

If none of them work for your printer you should still be able to print by specifying the the custom paper. See an example here: https://github.com/CodeMinion/Demo-Another-Brother-Prime/blob/master/lib/main.dart#L207

I used to use the CustomPaperInfo to print before we integrated the bin files so I would recommend giving them a try. 

Thanks again for reaching out and please don't hesitate to reach out if there is anything else I can help with.

**Comment by christiandjakou** [comment]
Thanks @CodeMinion for the quick feedback. 
Specifying the custom paper as explained in the example works! 
Just mentioning that Using the RJ_4030Ai papers did not work, I had the same errors. 
Marking this issue as resolved!

**Comment by CodeMinion** [comment]
Great to hear @christiandjakou ! Glad I could help. 

Thanks for the note on the RJ_4030Ai. 

Don't hesitate to reach out if you have any other questions or if there is anything else I can help with.
