### ISSUE TITLE
Multiple Print Without Cutting

### ISSUE THREAD

**Issue by berkanaslan** [CodeMinion/another_brother#39]
Hello, Thanks for supporting such a beautiful package!

I'm using the PT-E550W label printer over the Wi-Fi and here is the my settings:

```
printInfo.printerModel = Model.PT_E550W;
printInfo.printMode = PrintMode.FIT_TO_PAGE;
printInfo.port = Port.NET;
printInfo.labelNameIndex = PT.ordinalFromID(PT.W24.getId());
```
That's what I printed as a successfully thanks to the **qr_flutter** package:

```
QrValidationResult result = QrValidator.validate(data: "LABEL", version: QrVersions.auto, errorCorrectionLevel: QrErrorCorrectLevel.L);

QrPainter painter = QrPainter.withQr(
 qr: result.qrCode!,
 color: Colors.black,
 emptyColor: Colors.white,
 gapless: false,
);

ui.Image qrImage = await painter.toImage(2048);
await printer.printImage(qrImage);
```
Output: https://imgur.com/a/68fYYnQ

My problem is, I want to print barcodes in a synchronous manner as done here: https://youtu.be/pNuVyek06RI?t=425

But if the printImage(Image data) method is called inside the loop, a cutted label is output many times, not as a ordinally.

I'm not sure if this is a issue or a enhacement request. I would be very happy if you could enlighten me on this and help me. Thanks.

**Comment by berkanaslan** [comment]
Hi @CodeMinion. Thanks for your reply. 

I'm using Samsung Galaxy Tab S8.

Actualy, I tried both:


```
ui.Image qrImage = await painter.toImage(2048);

if (await printer.startCommunication()) {
  for (int i = 0; i < 2; i++) {
   await printer.printImage(qrImage);
  }
}

await printer.endCommunication();
```

And only printImage:

```
await printer.printImage(qrImage);
```

You can reach out full code:
https://gist.github.com/berkanaslan/d49ed6e9354c6bf96b51edeed0cf5559#file-pt-e550w-dart


Also, while researching, I found this document. Is it possible to chain print with the template and replace the text in the QR? If so, that will be fixed my issue. But I'm not sure, document too short.
https://support.brother.com/g/s/es/htmldoc/mobilesdk/guide/print-template.html

**Comment by CodeMinion** [comment]
Thanks for the details @berkanaslan.

I got an answer from Brother and it seems it can be done with a combination of **chainPrint** and **halfCut**. While we do have support for halfCut, the chainPrint property seems to have come in in version 4 of their library so we might need to migrate. However I'll take a look at the existing documentation further and see if I can find anything else.

I don't have the printer model you have so in the meantime could try setting halfCut to true and letting me know what outcome that has?

Thanks in advance,

**Comment by berkanaslan** [comment]
I'm grateful for you to talk to Brother and help. Tank You.

I can't try this right now because my tape is over. But, before I tried Halfcut = true and then the result had not changed.
(https://i.imgur.com/zi0ubrr.jpeg) May have had the effect of other combinations. I will have a new tape on weekdays and update the status. My goal will be to use halfCut without combination.

What is the compatibility of the another_brother for the upgrade to 4.0? Can we do this by providing an SDK upgrade or will we have to make a strong upgrade as starting at zero? I don't want to leave you alone in this upgrade process, on the contrary, I would like to help. At least for Android SDK.

**Comment by CodeMinion** [comment]
Happy to help @berkanaslan ! 

Thanks for the offer! The update will take quite a bit of effort due to the delta between versions but will definitely take you up on that offer if/when we make the switch. Currently I am exploring directly supporting the printers on native Dart as opposed to the current approach which is dependent on the Android and iOS SDK. Doing so will require a lot of effort but we do get some amazing returns on that investment like:

- Ability to print from any of the platforms supported by Flutter like Windows, Mac, Linux, Web, Android, and iOS instead of just the two we can today Android and iOS
- We inherently get feature parity between all platforms as opposed to the disparity between Android and iOS.
- And finally it makes it so another_brother doesn't have to be updated every time a new SDK version is released and be impacted by the respective design changes that come with them but instead we focus on updating when a new printer is released available.   

But in the meantime we do have some good news! 

With some additional help from Bob at Brother it turns out that another_brother can already support your use case with a bit of app code magic. 

Here are the configuration params (I don't have your printer model but I have a PT910BT which follows the same behavior):

First disable the cutting after every page:

```
var printInfo = PrinterInfo();
    printInfo.printerModel = Model.PT_P910BT;
    printInfo.printMode = PrintMode.FIT_TO_PAGE;
    // Disable cutting after every page
    printInfo.isAutoCut = false;
    // Disable end cut.
    printInfo.isCutAtEnd = false;
    // Allow for cutting mid page
    printInfo.isHalfCut = true;
    printInfo.port = Port.BLUETOOTH;
    // Set the label type.
    printInfo.labelNameIndex = PT.ordinalFromID(PT.W36.getId());
```

Then ensure your loop iterates n-1 time because we'll need the last print to cut the paper:
```
// We purposely print n-1 labels because we'll use the last print to cut the tape
    for (int i = 0; i < totalLabelsToPrint -1; i ++) {
      await printer.printImage(await loadImage('assets/brother_hack.png'));
    }
```

Finally reset the cutting parameters and print the last label:
```
printInfo.isAutoCut = false;
    printInfo.isCutAtEnd = true;
    printInfo.isHalfCut = false;
    await printer.setPrinterInfo(printInfo);
    await printer.printImage(await loadImage('assets/brother_hack.png'));
```

I have updated the Demo-Another-Brother with a sample for chain print which puts all of this together so you may check the full working code here: https://github.com/CodeMinion/Demo-Another-Brother-Prime/blob/master/lib/main.dart#L531

Thanks again for reaching out about this and all the detailed information. I'll leave this issue open until you have a chance to verify it on your end just in case anything comes up. So feel free to close it after that if all works well.

**Comment by berkanaslan** [comment]
OMG @CodeMinion! What a good person you are! As soon as my new label tape arrives, I'll try it and let you know. Whatever the results, I appreciate your help. See you soon!

**Comment by berkanaslan** [comment]
Hello again, @CodeMinion.

Thank you for your help.  This is the result:

![13131514-651A-4A16-8846-CE823A89CB0B](https://user-images.githubusercontent.com/42192003/205959071-b4c205ef-3982-4066-9fa8-1b31b3e300b8.jpeg)
