### ISSUE TITLE
Text and Image print

### ISSUE THREAD

**Issue by akabisdev** [CodeMinion/another_brother#40]
Is there a way we can print text along with imageAsset in a row

We are using PT_P701BT model.

For example like a ListTile, that has text and some trailing image, would like to print in that format

As of now I am able to print text and image asset, but the print is on the right side of the label, if we try to align the text to left, the text clips off. so. there is an empty space at starting and then the text comes. Also how can i remove space from the start. so if i am printing only text it comes on left side not on right side.

here is the how i initialize the printer

```
Future<void> initializePrinter() async {
    printerInfo.printerModel = pi.Model.PT_P710BT;
    printerInfo.paperSize = pi.PaperSize.CUSTOM;
    printerInfo.printMode = pi.PrintMode.FIT_TO_PAGE;
    printerInfo.orientation = pi.Orientation.LANDSCAPE;
    // Disable cutting after every page
    printerInfo.isAutoCut = false;
    // Disable end cut.
    printerInfo.isCutAtEnd = true;
    // Allow for cutting mid page
    printerInfo.isHalfCut = false;
    printerInfo.port = pi.Port.BLUETOOTH;
    // Set the label type.
    printerInfo.labelNameIndex = PT.ordinalFromID(PT.W12.getId());

    double width = 12.0;
    double rightMargin = 0.0;

    final Map<dynamic, dynamic> paperMap = {
      'printerModel': pi.Model.PT_P710BT.toMap(),
      'paperKind': pi.PaperKind.ROLL.toMap(),
      'unit': pi.Unit.Mm.toMap(),
      'tapeWidth': width,
      'tapeLength': 20.0,
      'rightMargin': rightMargin,
      'leftMargin': rightMargin,
      'topMargin': rightMargin,
      'bottomMargin': rightMargin,
      'labelPitch': rightMargin,
      'markPosition': rightMargin,
      'markHeight': rightMargin,
    };

    pi.CustomPaperInfo? customPaperInfo = pi.CustomPaperInfo.fromMap(paperMap);

    printerInfo.customPaperInfo = customPaperInfo;

    // Set the printer info so we can use the SDK to get the printers.
    await printer.setPrinterInfo(printerInfo);
    setState(() {
      printerSet = true;
    });
  }
```

and when print button is clicked :
      
   ```
Future<void> _print(
    List<pi.BluetoothPrinter> printers,
    pi.BluetoothPrinter selectedPrinter,
  ) async {
    try {

      // Get the IP Address from the first printer found.
      printerInfo.macAddress = printers.single.macAddress;

      await printer.setPrinterInfo(printerInfo);

      ///Text Style
      ui.TextStyle style = ui.TextStyle(
        color: Colors.black,
        fontSize: 60,
      );

      final paragraphStyle = ui.ParagraphStyle(
        textDirection: TextDirection.ltr,
      );

      final paragraphBuilder = ui.ParagraphBuilder(paragraphStyle)
        ..pushStyle(style)
        ..addText(widget.printItem.title);
      //..addPlaceholder(
      //20,
      //100,
      //PlaceholderAlignment.middle,
      //);
      ///paragraph constraints required, w/o it optimized out error
      const constraints = ui.ParagraphConstraints(width: 200);
      final paragraph = paragraphBuilder.build();
      paragraph.layout(constraints);

      ///Setting offset in negative doesn't help, as it clips of the initial characters of the text
      final status = await printer.printText(paragraph);

      print('Got Status : $status');
    } on Exception catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Something went wrong: ${e.toString()}'),
        ),
      );
    }
  }
```

Any suggestions

Thanks

**Comment by CodeMinion** [comment]
Hi @akabisdev,

Thanks for reaching out about this. I would recommend taking a look at the QR Label sample here https://github.com/CodeMinion/Print-QR-Label/blob/main/lib/main.dart#L190 In there we print a QR code image with three lines of text on its right.

You may use a PictureRecorder with a canvas to have full control of the position of the text and the image, then use send the generated image to be printed. This approach will give you the best control over the final print.

Hope this helps, but don't hesitate to reach out if there is anything else I can help with.

**Comment by akabisdev** [comment]
Hi, @CodeMinion.. Thank you for the quick response.. I have tried the example, it seem to be the working fine. But I have couple of queries : 

* Before print it uses around 25mm of label without print and then it prints the label
* And current print length is 35mm can we change this? like if we need 45mm 55mm 65mm length
* And the can we set text size dynamically?

**Comment by CodeMinion** [comment]
Hi @akabisdev , anytime, glad I could help.

Using the approach in the example you are in full control over how long your label is. Taking your printer's dpi you could calculate the number of pixels you need the image to be in order to reach your desired length.

The font size is also something you control, in the example you'll notice we use a text style from Flutter to specify the font parameters so you have access to all the properties available there like weight, size, family, etc.

As for the initial 25 mm you are seeing it is hard to say without more details but at first glance it sounds like it is either related to how your image is being created or how your paper is being configured so I would double check those. 

While doing these kinds of apps where I am rendering a label to print I find it helpful to display the label on my app before printing with a background color that contrasts with the label's background so I may better judge the final output before sending it to print. That normally lets me catch any additional margins that I might have missed.

Thanks again for all the questions. Don't hesitate to reach out if there is anything else I can help with,

**Comment by akabisdev** [comment]
Thank you very much @CodeMinion.. Your response helps a lot.. 🙏🏼
