### ISSUE TITLE
Any update on iOS build issues?

### ISSUE THREAD

**Issue by mikhael28** [CodeMinion/another_brother#65]
With the newer SDK release, I was wondering if there was any progress made on the build issues trying to run the local build on Apple Silicon MacBooks iOS simulators? Or, is this something that is wholly dependent on Brother, and not really something we can address from the consumer side unless we add in our own drivers somehow? 

Have you had any communication with Brother on this - have they expressed any indication or timeline for when this could be achieved? We have currently rolled our our printing solution to one customer, and plan to roll it out to another in a couple of months - would be nice to be able to fully test our build locally, without running on a physical device on a built ipa distribution.

**Comment by CodeMinion** [comment]
Hi @mikhael28 ,

Thanks for reaching out about this. I'd love to add your app to the another_brother list of apps so other developers can get some inspiration so if you have the link handy it would be super. 

With regards to the iOS simulator support,  on their recent release Brother seems to have added support for running on the iOS simulator. However, because I am not familiar with the configuration of the podspec, I have not been able to properly configure the pod to support both the device and simulator. 

If you have more familiarity with it the project is available here https://github.com/CodeMinion/BRLMPrinterKit 

Thanks again for reaching out,

**Comment by mikhael28** [comment]
Hey @CodeMinion It's been a while since we've updated, I think we locked at 0.32 - I will likely revisit the functionality in a few weeks, to see if I can somehow load the arm/rosetta build of the drivers conditionally in the pubspec. I think that's the issue? Would be nice to update the package then. My coworker is eager to resolve the issue of having to comment/uncomment the another_brother library while developing new features for. 

Here is a link to the app - it's called ARMS Mobile, short for Automated Railroad Management System. It's an industrial piece of software, primarily serving the railroad industry and also transloading, intermodal & warehousing. The printing functionality is a very small part of it - a way for a facility to print backup QR codes for their inventory, in case the original gets damaged. Also, they can print QR codes to serve as labels for parts of their facilities. I originally became aquainted with your software during the Hackathon in 2022, and remembered it when I had to do this integration. I was a little salty when Linus asked me to ship the test printer back, but I did drop out of the hackathon towards the end so what can you do. 

https://apps.apple.com/us/app/arms-mobile/id1615127530

**Comment by CodeMinion** [comment]
Hi @mikhael28 ,

Thanks for the link. I have added it to the ReadMe and will be included in the next release of another_brother.

**Comment by mikhael28** [comment]
Sounds good! If anyone has any updates on how to make iOS build on an apple silicon simulator, please post here lol
