### ISSUE TITLE
Error when printing PDF on iOs : ERROR_PRINTER_SETTING_NOT_SUPPORTED

### ISSUE THREAD

**Issue by alaindeseine** [CodeMinion/another_brother#66]
Hi @CodeMinion,

Got a problem today. The Android implementation of the print server work like a charm. 

But when executed on iOs (iPad) printPDF function rturn this error : 

````
{errorCode: {id: 38, name: ERROR_PRINTER_SETTING_NOT_SUPPORTED}, labelId: -1, labelType: -1, isACConnected: {id: -1, name: Unknown}, isBatteryMounted: {id: -1, name: Unknown}, batteryLevel: -1, batteryResidualQuantityLevel: -1, maxOfBatteryResidualQuantityLevel: -1}
````

Printer is a TD2125NWB.

can't find any feedback for this error on Google. Have you already have this problem ?

Sincerely

Alain Deseine.

**Comment by CodeMinion** [comment]
Hi @alaindeseine ,

Thanks for reaching out about this and apologies for the late reply.

It turned out the mapping for those printers was missing on the iOS side of another_brother. Version 1.0.3 of another_brother that was just published should resolve this. 

I don't own one of those printers for testing so could I trouble you to give that version a try to see if the issue is resolved?

Thanks again for your support,

**Comment by alaindeseine** [comment]
Hi @CodeMinion 

I just test with the 1.0.3 on a TD2125NWB printer and it work lije a charm! 

Thanks again for releasing this version.

Sincerely.

**Comment by CodeMinion** [comment]
Hi @alaindeseine ,

Glad to hear! Happy I could help.

Thanks again for reaching out about this and helping with the verification.
