### ISSUE TITLE
USB connection example

### ISSUE THREAD

**Issue by ebapp-dev** [CodeMinion/another_brother#69]
Can you help me with an example of a USB connection for the QL-800 to Android. I can't identify the API reference. Thanks.

**Comment by CodeMinion** [comment]
Hi @ebapp-dev ,

Thanks for reaching out about this. To print using USB the setup will follow the same approach as WIFI and BLUETOOTH but you'll instead use USB as the port. https://github.com/CodeMinion/Demo-Another-Brother/blob/main/lib/main.dart#L386

Because you can only have one printer connected there is no need to search so you can print right after the configuraiton.

Hope this helps but don't hesitate to reach out if there is anything else we can help with,
