### ISSUE TITLE
QL-800 Label format

### ISSUE THREAD

**Issue by GabrielRStabile** [CodeMinion/another_brother#93]
Hello!

I'm trying to print on QL-800 label printer with a 29x90 label size but I'm facing some issues with "ERROR_WRONG_LABEL". Could you provide me some help, please?

Thank you.

**Comment by CodeMinion** [comment]
Hi @GabrielRStabile ,

Could we trouble you to provide the snippet of code that you are using to print to the QL-800. 

Most often ERROR_WRONG_LABEL is an indication that we are passing a label to the printer that is different from the one currently loaded.

Thanks in advance,

**Comment by GabrielRStabile** [comment]
Hey @CodeMinion, I'm using the code above:

`
PrinterInfo printerInfo = PrinterInfo(
      printerModel: Model.QL_800,
      printMode: PrintMode.FIT_TO_PAPER,
      port: Port.USB,
    );

    printer.setPrinterInfo(printerInfo);
`

**Comment by CodeMinion** [comment]
Hi @GabrielRStabile ,

Thanks for sharing the code. That explains the error, the code provided does not specify the label that is currently used in your printer. 

For different print examples have a look at the demo application here https://github.com/CodeMinion/Demo-Another-Brother-Prime/blob/master/lib/main.dart#L432

Note that since you are using a QL-800 you'll need to use one of the labels from the QL-700 as the library does not include a QL-800. https://github.com/CodeMinion/another_brother/blob/main/lib/label_info.dart#L419

Thanks again for the additional info,

**Comment by GabrielRStabile** [comment]
Hey @CodeMinion, thank you for your support. Using the QL-700 label worked normally!

**Comment by CodeMinion** [comment]
Hi @GabrielRStabile,

Happy to help. 

Don't hesitate to reach out if there is anything else we can help with,
